services:
  app:
    build: .
    container_name: django_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

  static:
    image: nginx:stable-alpine
    container_name: static_server
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    command: ["nginx", "-g", "daemon off;"]
