version: '3.8'

services:
  app:
    image: python:3.11-slim
    container_name: django_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile

  static:
    image: nginx:stable-alpine
    container_name: static_server
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    command: ["nginx", "-g", "daemon off;"]
