# Generated by Django 5.1.2 on 2025-01-20 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('last_modified', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('space_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='app.space')),
            ],
        ),
    ]
